### ISSUE TITLE
In LOS_QueueCreate() function, the byte align issue

### ISSUE THREAD

**Issue by BaikalHu** [LiteOS/LiteOS#112]
Could 
uwRet = osQueueCreate(usLen, puwQueueID, (usMaxMsgSize + sizeof(UINT32)), &pstQueueCB);
change to
uwRet = osQueueCreate(usLen, puwQueueID, OS_MEM_ALIGN(usMaxMsgSize, sizeof(UINT32)), &pstQueueCB);

It comply the byte align. And it consume the less memory.

**Comment by lichao93** [comment]
It wasn't a issue. usMaxMsgSize add sizeof(UINT32) just leaving spaces for ‘\r\n’,and in LOS_MemAlloc() func will do memory align.
