### ISSUE TITLE
RISCV移植的情况如何

### ISSUE THREAD

**Issue by Ddnirvana** [LiteOS/LiteOS#116]
Hi，我看到在kernel目录下面已经有riscv的移植的代码了，想问一下现在LiteOS对RISCV的支持的情况还有移植的进展是怎样的？

**Comment by liuxuming** [comment]
已经移植成功了.

**Comment by Ddnirvana** [comment]
@liuxuming  感谢回复！你们现在的移植是用spike或者qemu-riscv的模拟的，还是在板子或者FPGA实现的RISCV上面做的呢？我看你们文档中riscv没有和riscv相关的说明呢。

**Comment by chaifangming** [comment]
Not an issue, close it for now.

**Comment by lofyer** [comment]
芯片是谁的？
