### ISSUE TITLE
C++ STL Support in LiteOs

### ISSUE THREAD

**Issue by soumyajuit** [LiteOS/LiteOS#193]
Hi,

I have gone through the LiteOs documentation. It seems it supports C++ programming environment. 
Hence my question is, is it possible to integrate C++ code with STL in the LiteOS environment.
I am trying to integrate some C++ code which uses C++ STLs extensively.

**Comment by Supowang08** [comment]
Sorry, The LiteOS opensource version can not support c++ STL.
