### ISSUE TITLE
MIPS

### ISSUE THREAD

**Issue by Wiz-IO** [LiteOS/LiteOS#513]
I'm trying to port LiteOS for MIPS ( Microchip PIC32 )
can you explain in detail the function LOS_StartToRun() 
or publish something like a C equivalent

**Comment by w00164089** [comment]
1. enable task schedule
2. schedule the first task

**Comment by Wiz-IO** [comment]
Thanks, but can you write this function on C
I am not good with ARM assembler and I need to translate to MIPS

**Comment by Wiz-IO** [comment]
IDA Pro deassembler give this code (approximately)
can you explain it in detail (???)

`
int LOS_StartToRun() {
    int (* func)(int, int, int, int); // ????
    OS_NVIC_SYSPRI2 = OS_NVIC_PENDSV_PRI; // ARM 
    g_bTaskScheduled = 1; // enable task schedule
    __asm{ MSR.W CONTROL, #2 } // current stack pointer
    g_stLosTask.pstRunTask = g_stLosTask.pstNewTask;
    LOS_TASK_CB * V = g_stLosTask.pstNewTask;
    g_stLosTask.pstNewTask->usTaskStatus |= OS_TASK_STATUS_RUNNING;
    int * R = (int *) ((char *) V->pStackPointer + 100); // ???
    int v7  = R[0];
    int v8  = R[1];
    int v9  = R[2];
    int v10 = R[3];
    func = (int (*) (int, int, int, int))R[6]; // ???
    R += 26; // ???
    __asm{ MSR.W PSP, R } // ARM Process Stack Pointer
    __enable_irq(); // global
    return func(v7, v8, v9, v10); // ???
}
`

**Comment by Wiz-IO** [comment]
LiteOS over Microchip PIC32MZ ( MIPS32 )

![liteos](https://user-images.githubusercontent.com/14574834/47844254-9f448400-ddca-11e8-8c93-83c0d91dcdff.png)

**Comment by w00164089** [comment]
The tasks scheduled well？ Great.！

**Comment by w00164089** [comment]
Can you please share your code your code. I believe people are interested in how LiteOS on MIPS is realized. And it will be a great help if you can post your code here. Thanks a lot!

**Comment by chaifangming** [comment]
Close this as this is not an issue.
