### ISSUE TITLE
Hwi宏定义在readme.md中与代码不一致

### ISSUE THREAD

**Issue by larzhang2** [LiteOS/LiteOS#58]
`OS_INCLUDE_HWI` and `OS_INCLUDE_HWI` mentioned in Readme.md both have changed, which are defined accordingly as `LOSCFG_PLATFORM_HWI` and `LOSCFG_PLATFORM_HWI_LIMIT` now. Please update um in line with source code.

**Comment by lichao93** [comment]
OS_INCLUDE_HWI and OS_INCLUDE_HWI mentioned in Readme.md？I can't find it.

**Comment by larzhang2** [comment]
sorry for mistake, they exist in HuaweiLiteOSKernelDevGuide.md
>编程示例
前提条件：
在los_config.h中，将OS_INCLUDE_HWI定义为YES。
在los_config.h中，设置最大硬中断个数OS_HWI_MAX_USED_NUM。
说明 目前的中断测试代码提供了基本框架，中断硬件初始化代码请用户根据开发板硬件情况在Example_Exti0_Init()函数中自行实现。 

But in los_config.h, I just could find#if defined (RAM_SIZE_LEVEL_0)
```
#define LOSCFG_PLATFORM_HWI                             NO
#elif defined(RAM_SIZE_LEVEL_1)
#define LOSCFG_PLATFORM_HWI                             YES
#elif defined(RAM_SIZE_LEVEL_2)
#define LOSCFG_PLATFORM_HWI                             YES
#else
#define LOSCFG_PLATFORM_HWI                             YES
#endif

/**
 * @ingroup los_config
 * Maximum number of used hardware interrupts, including Tick timer interrupts.
 */
#define LOSCFG_PLATFORM_HWI_LIMIT                       96
```

**Comment by zhoubo85** [comment]
I'm sorry for that,we did some code optimization，so in source code we deleted the macro OS_HWI_MAX_USED_NUM and OS_INCLUDE_HWI, but forgot update HuaweiLiteOSKernelDevGuide.md.
we will fix this later

**Comment by gustave-wang** [comment]
already fix. Thanks for you report.
