### ISSUE TITLE
Disable Bluetooth icon in main menu

### ISSUE THREAD

**Issue by asixta** [LiteOS/LiteOS#754]
I love the watch but I would like to decide when to connect to the phone to make the relevant message updates.
I'm not sure when the bluetooth is enabled, maybe just pinging very small amount of time during the day, but would that make sense to have an icon in the parameters to disable the bluetooth manually ?
My wife does not like all these waves ... and I always have to justify that this is 'only' bluetooth on my hand!
But being able to disable bluetooth would be great.

**Comment by chaifangming** [comment]
Hi asixta,

Thanks for your support of Huawei prodects :-)

But this repo is for LiteOS itself, not for the watch. You can contact customer service.

Best Regards,
Fangming

**Comment by chaifangming** [comment]
Close this issue as it is not for the LiteOS itself.
