### ISSUE TITLE
Death link

### ISSUE THREAD

**Issue by inkydragon** [LiteOS/LiteOS#756]
* **Describe the bug**
website 403：[Huawei LiteOS 知识产权政策](http://developer.huawei.com/ict/cn/site-iot/article/iot-intellectual-property-rights)

**Comment by chaifangming** [comment]
Hi Dear developer,

Thanks for your help. This issue should have been fixed.

Thanks,

**Comment by chaifangming** [comment]
This issue should have been fixed. Close for now.
