### ISSUE TITLE
支持M3,M4和M7内核所有芯片

### ISSUE THREAD

**Issue by ouening** [LiteOS/LiteOS#775]
为什么官方帮助文档上支持的M3、M7内核的芯片型号这么少？不应该是所有相同内核下的芯片都通用吗？就像freertos一样

**Comment by cruise2018** [comment]
是的，是通用的，但是目前我们没有针对所有的MCU进行适配

**Comment by ouening** [comment]
原来如此，那就是帮助文档说的不清楚，让人觉得只要那些芯片是可以用的
